[package]
name = "field-catalog"
version = "0.2.1"
description = "Field Catalog desktop"
authors = ["fieldcatalog"]
edition = "2021"
license-file = "../LICENSE.md"
publish = false

[lib]
name = "field_catalog_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
